version: "3.9"

services:
  backend:
    build: ./api
    container_name: backend
    # Запускаем Flask через python app.py, пусть в app.py уже есть app.run(host="0.0.0.0", port=5050)
    command: python app.py
    ports:
      - "5050:5050"
    env_file:
      - ./api/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run build
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=http://38.244.138.103:5050
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: dmosc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
