version: "3.9"

services:
  backend:
    build: ./api
    container_name: backend
    command: python app.py
    ports:
      - "5050:5050"
    env_file:
      - ./api/.env
    depends_on:
      - db
      - logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"
        tag: "backend"
    networks:
      - cafe-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run build
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=https://dmosc.ru/api
    networks:
      - cafe-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - cafe-network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: dmosc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cafe-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - cafe-network

  elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    networks:
      - cafe-network
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    hostname: logstash
    image: logstash:7.16.2
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5001:5000/tcp"
      - "9600:9600"
    networks:
      - cafe-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:rp
    networks:
      - cafe-network
    ports:
      - "5601:5601"

volumes:
  pgdata:
  esdata:

networks:
  cafe-network:
    driver: bridge
